sudo: required
language: java
install: true
jdk:
- oraclejdk8

script:
- mvn clean install -X -Djarsigner.skip=false checkstyle:check

after_success:
- mvn test jacoco:report coveralls:report

deploy:
- provider: script
  script: mvn -s ci-settings.xml deploy -X checkstyle:checkstyle
  skip_cleanup: true
  on:
    branch: master
    tags: true
- provider: releases
  api_key:
    secure: "YtK6gh4f6ax5JITgE6N3SIZUN3gzCp3meLfzWtRJmRlntU5VOQYnwzsL7CeVMxm/A+5uIalSRNrc+AqYpOYphmNYz2BDnEQDocKXugkbpH2N7FVGNBS8EXu7ZC2MR/0/sy1E43+trReFdPsNWx5kM04SsQB61aA2StwESSWz7x5ZbU2qk+d1N5NWa3qDo1Mig9N/6qdkvef8y+XavbQus9F9cGUdspminmriFgg9x4otkHD+9f5YhfITpf0Zt00XO/wRkckFTh1un8B56dTJ7JVnMatwM+HGydSZ3KNquZobT400V8nnO3a2CsjzjhSSULklv9ASzVv5D5p6oZpAuUOlIIqsVQzxCdLq/qRJCgjvphmAsX5MBzE9sRqaK+HLXcN2Bs0sQzj7tozQgECBv/9dUrQ7F/wvegNI6HqLHF66YmR+JMpFGab1RlvqZ+SKB7TwY67kdZkHJxaxfjc0/y7IO0Fdiigw8qQNfTSQ+oRPyGMwGKnMDeNHKeJ67LWNGjyjprG/Ywh6zgwEYnAIiwEncOMhdRGSobKqeYU3o4uOGD7zLnMC2pLtPhi+ymj4tEOjmpNmtZn69Q6J177i4cVJNjYPXuXVcwM/JxmxZU7u0XwomV6LVkWQKx9qmwET0gT1uX1sxC1IPmQA/77uKQNqFGRydm/rCHcO5lEe1Kc="
  file_glob: true
  file:
  - "target/concat-*.jar"
  - "target/*.sha256"
  - "target/checksum-sha256.txt"
  skip_cleanup: true
  on:
    branch: master
    tags: true

cache:
  directories:
  - $HOME/.m2

notifications:
  slack:
    secure: "eQL4s+1hwUIvPoFok5ridSE2Rheyb1mcjl432FRYWIxAEcAjWB0FFnvZJMwZCEL5wLrEWu9PBEerdY81oN3uSR2J616pcji1DLSmQ52OBvQnBFmxzdqrhCGKJJQidhBQq3+GXBHnhQRP1J4FXkFVXAiQnxPDM+LKaSwi88VLQLsI7RqQ54HcF+UT3jv39HsIZy7eWaHTmeE+9QiS9acEIwzZmAGwtE4QAPBBSSLH+MGcVZROyAoWxf3ysNoId+ZJNvzMvg7QRSZX+FQADDbbAsCWDwXFNttu3mJe6PEQfSI/QlU/cc2WMnkqss6i07gd0I65FduFTnDUj91XnlQXAFiympRvygPgiDDf/X6KuZn6wB2i8VXEX3P/MbcmwMfGecNusbATvrTcpU+8K6uQQ6G9Yu90Iq0+AIOeM5poeG/DDOmObeMbcBPeRh9+IMYIo3d7/VJCCampSztJY2eQV6a3c6BXzaWmw3/617pF1AF5D1lqHSWCS0tRXE3AOk/xCMVaACEuKWch2I/oZZQORcZPPAlggzxOEBWDUEzqXsPiDdlJtGMPnri2vciXNFIeX0DpAhI/lD1Ytiw41PFvbUQNG0uSlOjDqi3nqrrOy3NESkYCJAMJyoMFWZ2UjyIGiod03NC82nhhEjpEClICq8YKJr4MrX2tYWxltUrbvmw="
  email: false
